### ISSUE TITLE
[bootstrap] kernels listed but have broken links

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#65]
https://bootstrap.ninja.tf/images

example: https://bootstrap.ninja.tf/kernel/zero-os-development-zos-v3-generic-9748df1563.efi
probably Flask version issue

```
TypeError
TypeError: send_from_directory() missing 1 required positional argument: 'path'

Traceback (most recent call last)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/bootstrap/bootstrap.py", line 179, in download
return send_from_directory(directory=config['kernel-path'], filename=filename)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
```

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people

**Comment by maxux** [comment]
Fixed via https://github.com/threefoldtech/0-bootstrap/commit/8e1f65649d72db92915a2fef053d9e23bcd4ae0f

**Comment by coesensbert** [comment]
confirmed
